version: 2
registries:
  npm-registry-npm-int-remitly-com:
    type: npm-registry
    url: https://npm.int.remitly.com
    token: "${{secrets.NPM_REGISTRY_NPM_INT_REMITLY_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "15:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  registries:
  - npm-registry-npm-int-remitly-com
